version: "3.7"
services:
    web:
        restart: unless-stopped
        build: .
        ports:
        - "8011:5000"
        volumes:
        - .:/code
        environment:
            FLASK_ENV: development
